#!/usr/bin/env bash
# Fetches and builds the third-party tools used to verify this implementation:
# - The qifs corpus: QIF inputs plus encoded outputs from other QPACK
#   implementations (https://github.com/qpackers/qifs)
# - ls-qpack's interop-encode/interop-decode CLI tools, used as an
#   independent reference implementation (https://github.com/litespeedtech/ls-qpack)
# - nghttp3's qpack CLI tool, as a second independent reference and a
#   benchmark target (https://github.com/ngtcp2/nghttp3)
# Everything is placed in test/tools/, which is gitignored.
set -euo pipefail
cd "$(dirname "$0")/.."

QIFS_REPO=https://github.com/qpackers/qifs.git
QIFS_COMMIT=da52cd936b3e34dac7ac12aa8066fc57676af106
LSQPACK_REPO=https://github.com/litespeedtech/ls-qpack.git
LSQPACK_TAG=v2.6.5
NGHTTP3_REPO=https://github.com/ngtcp2/nghttp3.git
NGHTTP3_TAG=v1.17.0

TOOLS=test/tools
PINS="$QIFS_COMMIT $LSQPACK_TAG $NGHTTP3_TAG v3"

if [ -f "$TOOLS/.pins" ] && [ "$(cat "$TOOLS/.pins")" = "$PINS" ]; then
    echo "Test tools already set up (test/tools/.pins matches) - skipping."
    exit 0
fi

rm -rf "$TOOLS"
mkdir -p "$TOOLS/bin"

echo "Fetching qifs corpus at $QIFS_COMMIT..."
git init -q "$TOOLS/qifs"
git -C "$TOOLS/qifs" fetch -q --depth 1 "$QIFS_REPO" "$QIFS_COMMIT"
git -C "$TOOLS/qifs" checkout -q FETCH_HEAD

echo "Fetching ls-qpack at $LSQPACK_TAG..."
git clone -q --depth 1 --branch "$LSQPACK_TAG" --recurse-submodules \
    --shallow-submodules "$LSQPACK_REPO" "$TOOLS/ls-qpack"

echo "Building ls-qpack interop tools..."
LSQ="$TOOLS/ls-qpack"
cc -O2 -I"$LSQ" -I"$LSQ/deps/xxhash" \
    "$LSQ/lsqpack.c" "$LSQ/deps/xxhash/xxhash.c" "$LSQ/bin/interop-encode.c" \
    -lm -o "$TOOLS/bin/interop-encode"
cc -O2 -I"$LSQ" -I"$LSQ/test" -I"$LSQ/deps/xxhash" \
    "$LSQ/lsqpack.c" "$LSQ/deps/xxhash/xxhash.c" "$LSQ/bin/interop-decode.c" \
    -lm -o "$TOOLS/bin/interop-decode"

"$TOOLS/bin/interop-encode" -h > /dev/null 2>&1 || { echo "interop-encode failed to run"; exit 1; }
"$TOOLS/bin/interop-decode" -h > /dev/null 2>&1 || { echo "interop-decode failed to run"; exit 1; }

echo "Fetching nghttp3 at $NGHTTP3_TAG..."
git clone -q --depth 1 --branch "$NGHTTP3_TAG" "$NGHTTP3_REPO" "$TOOLS/nghttp3"
git -C "$TOOLS/nghttp3" submodule update -q --init --depth 1 lib/sfparse

echo "Building nghttp3 qpack tool..."
NG="$TOOLS/nghttp3"

# The example decoder never drains its internal decoder-stream buffer, and
# the library aborts when that exceeds max(max_concurrent_streams, 100)*20
# bytes - so with the default of 0, offline inputs with over ~1000
# acknowledgeable field sections fail spuriously (a real connection flushes
# acknowledgments continuously). Raise the limit so large benchmark inputs
# work; this doesn't affect QPACK semantics.
sed -i 's|nghttp3_qpack_decoder_new(&dec_, max_dtable_size_, max_blocked_, mem_)|[\&]{ auto r = nghttp3_qpack_decoder_new(\&dec_, max_dtable_size_, max_blocked_, mem_); if (r == 0) nghttp3_qpack_decoder_set_max_concurrent_streams(dec_, 10000000); return r; }()|' \
    "$NG/examples/qpack_decode.cc"
grep -q "set_max_concurrent_streams" "$NG/examples/qpack_decode.cc" \
    || { echo "nghttp3 qpack_decode patch failed to apply"; exit 1; }
# The tool's version.h is normally generated by autotools/cmake:
sed -e "s/@PACKAGE_VERSION@/${NGHTTP3_TAG#v}/" -e 's/@PACKAGE_VERSION_NUM@/0/' \
    "$NG/lib/includes/nghttp3/version.h.in" > "$NG/lib/includes/nghttp3/version.h"

NG_DEFS="-DHAVE_ARPA_INET_H -DHAVE_NETINET_IN_H"
mkdir -p "$NG/obj"
for f in "$NG"/lib/*.c "$NG/lib/sfparse/sfparse.c"; do
    obj="$NG/obj/$(basename "${f%.c}").o"
    cc -O2 $NG_DEFS -I"$NG/lib" -I"$NG/lib/includes" -c "$f" -o "$obj"
done
g++ -O2 -std=c++20 $NG_DEFS -I"$NG/lib" -I"$NG/lib/includes" -I"$NG/examples" \
    "$NG/examples/qpack.cc" "$NG/examples/qpack_encode.cc" \
    "$NG/examples/qpack_decode.cc" "$NG/examples/util.cc" \
    "$NG"/obj/*.o -o "$TOOLS/bin/nghttp3-qpack"

"$TOOLS/bin/nghttp3-qpack" --help > /dev/null 2>&1 || { echo "nghttp3-qpack failed to run"; exit 1; }

echo "$PINS" > "$TOOLS/.pins"
echo "Test tools ready in $TOOLS/."
